config {
    type: "incremental",
    tags: [dataform.projectConfig.vars.environment],
    database: dataform.projectConfig.vars.source_database,
    schema: dataform.projectConfig.vars.target_flattened_dataset,
    bigquery: {
        partitionBy: "event_date",
        requirePartitionFilter : true,
    },
    dependOnDependencyAssertions: true,
    dependencies: ["navigation_events_assertions"]  
}

SELECT
* EXCEPT(is_consented)
FROM ${ref("navigation_events_processing")} 
