config {
    type: "incremental",
    tags: [dataform.projectConfig.vars.environment],
    database: dataform.projectConfig.vars.processing_database,
    schema: dataform.projectConfig.vars.processing_schema,
    bigquery: {
        partitionBy: "event_date",
        requirePartitionFilter : true,
        updatePartitionFilter: "event_date = partition_event_date"
    },
    uniqueKey: [
        "event_date",
        "event_name",
        "cleaned_page_location",
        "canonical_url",
        "link_domain",
        "link_url",
        "type",
        "outbound"
    ],
    dependOnDependencyAssertions: true
}

pre_operations {
  DECLARE partition_event_date DATE;
  SET partition_event_date = (
    SELECT MIN(event_date)
    FROM  ${ref("staging_navigation_events")}
    );
}

SELECT *
FROM ${ref("staging_navigation_events")}