config {
    type: "incremental",
    tags: [dataform.projectConfig.vars.environment],
    database: dataform.projectConfig.vars.source_database,
    schema: dataform.projectConfig.vars.target_flattened_dataset,
    bigquery: {
        partitionBy: "event_date",
        requirePartitionFilter : true,
    },
    dependOnDependencyAssertions: true,
    dependencies: ["page_summaries_processing"]
}

SELECT
* except(is_consented)
FROM ${ref("page_summaries_processing")}