config {
  type: "table",
  tags: [dataform.projectConfig.vars.environment],
  database: dataform.projectConfig.vars.source_database,
  schema: dataform.projectConfig.vars.source_ga4_prod_schema,
}

pre_operations {
  DECLARE _table_suffix STRING DEFAULT "YYYYMMDD";
  SET _table_suffix = (
    SELECT table_name
    FROM  ${ref("ga4_process_shard")} 
    ); 
}

SELECT
    *,
    _TABLE_SUFFIX as table_suffix
FROM ${ref("events_*")}
WHERE _TABLE_SUFFIX = _table_suffix