config {
  type: "table",
  tags: [dataform.projectConfig.vars.environment],
  database: dataform.projectConfig.vars.processing_database,
  schema: dataform.projectConfig.vars.processing_schema,
}

SELECT 
  *,

  (CASE
   WHEN (REGEXP_CONTAINS(document_type, 'smart_answer|_transaction|special_route')) THEN (SPLIT(SPLIT(REGEXP_REPLACE(page_location, 'https://www.gov.uk', ''),'?')[SAFE_OFFSET(0)],'#')[SAFE_OFFSET(0)])
   WHEN (REGEXP_CONTAINS(document_type, 'guide|travel_advice')) AND REGEXP_CONTAINS(page_location, '/print') THEN (SPLIT(SPLIT(REGEXP_REPLACE(page_location, 'https://www.gov.uk', ''),'?')[SAFE_OFFSET(0)],'#')[SAFE_OFFSET(0)])
   WHEN (REGEXP_CONTAINS(document_type, 'manual')) AND REGEXP_CONTAINS(page_location, '/updates') THEN (SPLIT(SPLIT(REGEXP_REPLACE(page_location, 'https://www.gov.uk', ''),'?')[SAFE_OFFSET(0)],'#')[SAFE_OFFSET(0)])
   ELSE (COALESCE((REGEXP_REPLACE(canonical_url, 'https://www.gov.uk', '')), (SPLIT(SPLIT(REGEXP_REPLACE(page_location, 'https://www.gov.uk', ''),'?')[SAFE_OFFSET(0)],'#')[SAFE_OFFSET(0)])))
   END) AS cleaned_page_location,

   SPLIT(REGEXP_REPLACE(page_referrer, 'https://www.gov.uk', ''),'?')[SAFE_OFFSET(0)] AS cleaned_page_referrer,

--Field no longer required but column retained for historic data
CAST(NULL AS STRING) AS full_link_URL

FROM ${ref("ga4_flattening_5")}