config {
  type: "table",
  tags: [dataform.projectConfig.vars.environment],
  database: dataform.projectConfig.vars.source_database,
  schema: dataform.projectConfig.vars.source_ga4_prod_schema,
}

pre_operations {
  DECLARE t_suffix STRING DEFAULT "YYYYMMDD";
  SET t_suffix = (
    SELECT table_name
    FROM  ${ref("ga4_process_shard")} 
    ); 
}

SELECT
    *,
    _TABLE_SUFFIX as shard
FROM ${ref("events_*")}
WHERE _TABLE_SUFFIX = t_suffix