config {
    type: "table",
    tags: [dataform.projectConfig.vars.environment],
    database: dataform.projectConfig.vars.processing_database,
    schema: dataform.projectConfig.vars.processing_schema,
    bigquery: {
        partitionBy: "event_date",
        requirePartitionFilter : true,
        clusterBy: ["event_name"]
    }
}
 
SELECT 
  *
FROM ${ref("ga4_augmenting")}
where is_consented = 'true'