config {
    type: "assertion",
    tags: [dataform.projectConfig.vars.environment],
    database: dataform.projectConfig.vars.processing_database,
    schema: dataform.projectConfig.vars.processing_schema,
}

WITH 

all_partitions AS (

  SELECT 'page_summaries' AS table_name, event_date
  FROM ${ref("page_summaries")}
  WHERE event_date IS NOT NULL
  GROUP BY table_name, event_date

  UNION ALL

  SELECT 'navigation_events', event_date
  FROM ${ref("navigation_events")}
  WHERE event_date IS NOT NULL
  GROUP BY event_date

  UNION ALL

  SELECT 'search_events', event_date
  FROM ${ref("search_events")}
  WHERE event_date IS NOT NULL
  GROUP BY event_date

  UNION ALL

  SELECT 'ga4_content_data', 
  PARSE_DATE('%Y-%m-%d', CAST(the_date AS STRING)) AS event_date
  FROM ${ref("ga4_content_data")}
  WHERE the_date IS NOT NULL
  GROUP BY event_date
  ),

max_partition as (SELECT
  MAX(PARSE_DATE('%Y%m%d', partition_id)) AS max_event_date
FROM `${dataform.projectConfig.vars.source_database}.${dataform.projectConfig.vars.source_ga4_prod_schema}.INFORMATION_SCHEMA.PARTITIONS`
WHERE table_name = 'partitioned_events'
  AND partition_id IS NOT NULL
  AND partition_id != '__NULL__')

SELECT 
b.max_event_date,
count(a.event_date) as count
FROM 
all_partitions a,
max_partition b
WHERE b.max_event_date = a.event_date
GROUP BY b.max_event_date
HAVING COUNT(table_name) > 0



